[package]
name = "moonbeam-rpc-debug"
version = '0.1.0'
authors = ['PureStake']
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
tokio = { version = "0.2.21", features = ["sync", "time"] }
futures = { version = "0.3", features = ["compat"] }
jsonrpc-core = "15.0.0"

ethereum = { version = "0.7.1", default-features = false, features = ["with-codec"] }
ethereum-types = "0.11.0"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

moonbeam-rpc-core-debug = { path = "../../rpc-core/debug" }
moonbeam-rpc-primitives-debug = { path = "../../../primitives/rpc/debug" }
fc-consensus = { git = "https://github.com/purestake/frontier", branch = "moonbeam-v0.8.2" }
fc-db = { git = "https://github.com/purestake/frontier", branch = "moonbeam-v0.8.2" }
fc-rpc = { git = "https://github.com/purestake/frontier", branch = "moonbeam-v0.8.2" }
fp-rpc = { git = "https://github.com/purestake/frontier", branch = "moonbeam-v0.8.2" }
