[dependencies]
derive_more = '0.15.0'
log = "0.4.13"
codec = { package = 'parity-scale-codec', version = '2.0.0' }
structopt = "0.3.8"
serde = { version = "1.0.119", features = ["derive"] }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
# RPC related dependencies
jsonrpc-core = "15.1.0"
serde_json = "1.0"
tokio = { version = "0.2.13", features = ["macros", "sync"] }

async-io = "1.3"

jsonrpc-pubsub = "15.1.0"
ethereum-types = "0.11.0"
ethereum = { version = "0.7.1", features = ["with-codec"] }

pallet-evm  = { package = "pallet-evm", git = "https://github.com/purestake/frontier", branch = "joshy-substrate-2be8fcc4" }
pallet-ethereum = { package = "pallet-ethereum", git = "https://github.com/purestake/frontier", branch = "joshy-substrate-2be8fcc4" }

nimbus-consensus = { git = "https://github.com/purestake/cumulus", branch = "nimbus" }
pallet-author-inherent = { git = "https://github.com/purestake/cumulus", branch = "nimbus" }
# TODO we should be able to depend only on the primitives crate once we move the inherent data provider there.
nimbus-primitives = { git = "https://github.com/purestake/cumulus", branch = "nimbus" }

fc-consensus = { git = "https://github.com/purestake/frontier", branch = "joshy-substrate-2be8fcc4" }
fp-consensus = { git = "https://github.com/purestake/frontier", branch = "joshy-substrate-2be8fcc4" }
fc-rpc-core = { git = "https://github.com/purestake/frontier", branch = "joshy-substrate-2be8fcc4" }
fc-rpc = { git = "https://github.com/purestake/frontier", branch = "joshy-substrate-2be8fcc4" }
fp-rpc = { git = "https://github.com/purestake/frontier", branch = "joshy-substrate-2be8fcc4" }
fc-db = { git = "https://github.com/purestake/frontier", branch = "joshy-substrate-2be8fcc4" }
fc-mapping-sync = { git = "https://github.com/purestake/frontier", branch = "joshy-substrate-2be8fcc4" }

moonbeam-rpc-txpool = { path = "../client/rpc/txpool" }
moonbeam-rpc-primitives-txpool = { path = "../primitives/rpc/txpool" }
moonbeam-rpc-trace = { path = "../client/rpc/trace" }
moonbeam-rpc-debug = { path = "../client/rpc/debug" }
moonbeam-rpc-primitives-debug = { path = "../primitives/rpc/debug" }

sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

cumulus-primitives-parachain-inherent = { git = "https://github.com/purestake/cumulus", branch = "nimbus" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/purestake/cumulus", branch = "nimbus" }


[dependencies.frame-benchmarking]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.frame-benchmarking-cli]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.parachain-runtime]
path = '../runtime'
version = '2.0.0'

[dependencies.pallet-transaction-payment-rpc]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sc-basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '0.9.0'

[dependencies.sc-chain-spec]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sc-cli]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '0.9.0'

[dependencies.sc-client-api]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sc-consensus]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '0.9.0'

[dependencies.sc-executor]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '0.9.0'

[dependencies.sc-keystore]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sc-rpc]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sc-rpc-api]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '0.9.0'

[dependencies.sc-service]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '0.9.0'

[dependencies.sc-telemetry]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sc-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sc-tracing]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sc-network]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'

[dependencies.sp-api]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sp-block-builder]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sp-blockchain]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sp-consensus]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '0.9.0'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sp-timestamp]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sp-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.sp-trie]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[dependencies.substrate-frame-rpc-system]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
branch = 'rococo-v1'
version = '3.0.0'

# Frontier dependencies

# Cumulus dependencies
[dependencies.cumulus-client-consensus-relay-chain]
git = "https://github.com/purestake/cumulus"
branch = "nimbus"

[dependencies.cumulus-client-collator]
git = "https://github.com/purestake/cumulus"
branch = "nimbus"

[dependencies.cumulus-client-cli]
git = "https://github.com/purestake/cumulus"
branch = "nimbus"

[dependencies.cumulus-client-network]
git = "https://github.com/purestake/cumulus"
branch = "nimbus"

[dependencies.cumulus-primitives-core]
git = "https://github.com/purestake/cumulus"
branch = "nimbus"

[dependencies.cumulus-client-service]
git = "https://github.com/purestake/cumulus"
branch = "nimbus"

# Polkadot dependencies
[dependencies.polkadot-primitives]
git = "https://github.com/paritytech/polkadot"
branch = 'rococo-v1'

[dependencies.polkadot-service]
git = "https://github.com/paritytech/polkadot"
branch = 'rococo-v1'

[dependencies.polkadot-cli]
git = "https://github.com/paritytech/polkadot"
branch = 'rococo-v1'

[dependencies.polkadot-test-service]
git = "https://github.com/paritytech/polkadot"
branch = 'rococo-v1'

[dependencies.polkadot-parachain]
git = "https://github.com/paritytech/polkadot"
branch = 'rococo-v1'

[[bin]]
name = 'parachain-collator'

[package]
authors = ['Anonymous']
build = 'build.rs'
description = 'A new Cumulus FRAME-based Substrate node, ready for hacking.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'parachain-collator'
repository = 'https://github.com/substrate-developer-hub/substrate-parachain-template'
version = '2.0.0'
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[features]
default = []
runtime-benchmarks = ['parachain-runtime/runtime-benchmarks']
